### ISSUE TITLE
Refactoring causes troubles with Spring @Autowired (classes have been moved to sibling namespace instead of sub-packages)

### ISSUE THREAD

**Issue by MarkusTiede** [ergon/airlock-waf-kubernetes-openshift-integration#15]
Moving the application resolves this: https://github.com/baloise-incubator/airlock-waf-kubernetes-openshift-integration/commit/36454be377254ab81e78c20880195aeab0b3b701

**Comment by orltom** [comment]
Hi Markus, the pull request https://github.com/ergon/airlock-waf-kubernetes-openshift-integration/pull/18 fix this issue
