### ISSUE TITLE
The waf-client java module should not be initialized with Dependency Injection mechanism 

### ISSUE THREAD

**Issue by orltom** [ergon/airlock-waf-kubernetes-openshift-integration#16]
Currently the waf-client module use Spring DI to initialize a Client. But should not be necessary...

- Move KubernetesContext to event-listener module
- AirlockWAFClient should have only a constructor with AirlockWAFContext and a RestTemplate instance.
- Remove Auto Injection Annotations

**Comment by dieti80** [comment]
Closed this issue because the repo is not maintained anymore.
